# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/solutions/Csharp/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/solutions/Go/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/solutions/Python/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/solutions/TypeScript/"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "nuget"
    directory: "/exercises/Csharp/NotesApi/NotesApi"
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget"
    directory: "/exercises/Csharp/NotesApi/NotesTests"
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget"
    directory: "/exercises/Csharp/NotesApi/NotesTypes"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "gomod"
    directory: "/exercises/Go"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "pip"
    directory: "/exercises/Python"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "npm"
    directory: "/exercises/TypeScript"
    schedule:
      interval: "monthly"
