name: C# Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ASPNETCORE_ENVIRONMENT: CI

jobs:
  build:
    name: API Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - run: dotnet build NotesApi
        working-directory: './exercises/Csharp'

  lint:
    name: API Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - run: dotnet format NotesApi
        working-directory: './exercises/Csharp'

  test:
    name: API Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - run: dotnet test NotesApi
        working-directory: './exercises/Csharp'
